repo_url: https://github.com/oxfordmmm/gnomonicus
repo_name: gnomonicus
site_name: Gnomonicus Documentation
docs_dir: docs/
site_dir: public/

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

nav:
  - Home: readme.md
  - Code Reference: reference/
  - CLI: bin.md
  - Output files: outputs.md

extra:
  version:
    provider: jeremy
plugins:
  - include-markdown
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [gnomonicus, bin]