name: Build gnomonicus Docker images
# Heavily based on the build action for SARS-CoV2_Workflows (https://github.com/oxfordmmm/SARS-CoV2_workflows/blob/main/.github/workflows/build.yaml)

#We only want to build this container if we have a successful PyPI package
on:
  workflow_run:
    workflows: ["Build and release on PyPI"]
    types:
      - completed

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - 
        name: Find Latest Tag
        uses: oprypin/find-latest-tag@v1.1.0
        with:
          repository: oxfordmmm/gnomonicus  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: gnomonicus  # The step ID to refer to later.
      -  run: echo ${{steps.gnomonicus.outputs.tag}} #Debugging...
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: environments/Dockerfile
          tags: |
            oxfordmmm/gnomonicus:latest
            oxfordmmm/gnomonicus:${{steps.gnomonicus.outputs.tag}}
          push: true
          no-cache: true
